name: Assign new bug or updater

on:
  issues:
    types:
      - opened

jobs:
  add-bug-to-project:
    runs-on: ubuntu-latest
    steps:
    - name: Add bug or maintenance issue to project
      uses: actions/add-to-project@main
      with:
        project-url: https://github.com/users/NicolasOmar/projects/1
        github-token: ${{ secrets.ADD_TO_MY_PETS_PROJECT }}
        labeled: bug, dependencies
        label-operator: OR