name: Check builds

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1/6 | Checkout repo
      uses: actions/checkout@v5
    - name: 2/6 | Setup Node environment
      uses: actions/setup-node@v5
      with:
        node-version: latest
    - name: 3/6 | Install depedencies
      run: npm ci
    - name: 4/6 | Run code styling check script
      run: npm run prettier
    - name: 5/6 | Run static code quality check script
      run: npm run lint
    - name: 6/6 | Run build package script
      run: npm run build