name: Check tests coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: 1/5 | Checkout repo
      uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: 2/5 | Setup Node environment
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: 3/5 | Install depedencies
      run: npm install

    - name: 4/5 | Run unit tests suite
      run: npm run test:ci

    - name: 5/5 | Run Codecov Uploader
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage-final.json
        flags: unittests
        fail_ci_if_error: true
        verbose: true
